import { defineThemePreset, ThemeVars, ThemePreset } from './core'

export const THEME_DEFAULT = defineThemePreset({
  [ThemeVars.BrandSoramitsuRed]: '#E3232C',
  [ThemeVars.BrandPMSBlack]: '#2D2926',
  [ThemeVars.BrandUltraBlack]: '#0D0248',
  [ThemeVars.BrandWhite]: 'white',
  [ThemeVars.BrandPolkaswapPink]: '#ED145B',
  [ThemeVars.ColorThemeAccent]: `#D0021B`,
  [ThemeVars.ColorThemeAccentHover]: `#C6021A`,
  [ThemeVars.ColorThemeAccentPressed]: `#BB0218`,
  [ThemeVars.ColorThemeAccentFocused]: `#B10217`,
  [ThemeVars.ColorThemeSecondary]: `#FAE6E8`,
  [ThemeVars.ColorThemeSecondaryHover]: `#F6CCD1`,
  [ThemeVars.ColorThemeSecondaryPressed]: `#F1B3BB`,
  [ThemeVars.ColorThemeSecondaryFocused]: `#EC9AA4`,
  [ThemeVars.ColorBaseContentPrimary]: `#2D2926`,
  [ThemeVars.ColorBaseContentSecondary]: `#53565A`,
  [ThemeVars.ColorBaseContentTertiary]: `#75787B`,
  [ThemeVars.ColorBaseContentQuaternary]: `#A3A4A8`,
  [ThemeVars.ColorBaseBackground]: `#F5F7F8`,
  [ThemeVars.ColorBaseDarkBackground]: `#4E4E4E`,
  [ThemeVars.ColorBaseBorderPrimary]: `#DDE0E1`,
  [ThemeVars.ColorBaseBorderSecondary]: `#ECEFF0`,
  [ThemeVars.ColorBaseBackgroundHover]: `#ECEFF0`,
  [ThemeVars.ColorBaseDisabled]: `#F5F7F8`,
  [ThemeVars.ColorBaseOnDisabled]: `#75787B`,
  [ThemeVars.ColorBaseOnAccent]: `#FFFFFF`,
  [ThemeVars.ColorUtilityBody]: `#FFFFFF`,
  [ThemeVars.ColorUtilitySurface]: `#FFFFFF`,
  [ThemeVars.ColorUtilityOverlay]: `rgba(0, 0, 0, 0.45)`,
  [ThemeVars.ColorStatusSuccess]: `#009900`,
  [ThemeVars.ColorStatusWarning]: `#FF9900`,
  [ThemeVars.ColorStatusError]: `#FF0000`,
  [ThemeVars.ColorStatusSuccessBackground]: `#CCEDCC`,
  [ThemeVars.ColorStatusWarningBackground]: `#FFE3B8`,
  [ThemeVars.ColorStatusErrorBackground]: `#FFF9FA`,

  // font size

  [ThemeVars.FontSize4xl]: '40px',
  [ThemeVars.FontSize3xl]: '36px',
  [ThemeVars.FontSize2xl]: '30px',
  [ThemeVars.FontSizeXl]: '24px',
  [ThemeVars.FontSizeLg]: '18px',
  [ThemeVars.FontSizeMd]: '16px',
  [ThemeVars.FontSizeSm]: '14px',
  [ThemeVars.FontSizeXs]: '12px',
  [ThemeVars.FontSize2xs]: '10px',

  // [ThemeVars.SizeMini]: `24px`,
  // [ThemeVars.SizeSmall]: `32px`,
  // [ThemeVars.SizeMedium]: `40px`,
  // [ThemeVars.SizeBig]: `56px`,
  // [ThemeVars.BasicSpacing]: `8px`,
  // [ThemeVars.BorderRadiusMini]: `$s-border-radius-base`,
  // [ThemeVars.BorderRadiusSmall]: `$s-border-radius-base * 2`,
  // [ThemeVars.BorderRadiusMedium]: `$s-border-radius-base * 3`,
  // [ThemeVars.BorderRadiusBig]: `$s-border-radius-base * 4`,
  // [ThemeVars.ShadowColorDark]: `rgba(0, 0, 0, 0.1)`,
  [ThemeVars.ShadowTokenIcon]: 'black', // FIXME
  // [ThemeVars.ShadowColorDarkLight]: `rgba(0, 0, 0, 0.02)`,
  // [ThemeVars.ShadowColorLight]: `rgba(255, 255, 255, 1)`,
  // [ThemeVars.ShadowColorLightDark]: `rgba(255, 255, 255, 0.8)`,
  // [ThemeVars.ShadowElement]: `-1px -1px 1px var(${ThemeVars.ShadowColorDarkLight}), 1px 1px 3px var(${ThemeVars.ShadowColorDark}), inset 1px 1px 2px var(${ThemeVars.ShadowColorLightDark})`,
  // [ThemeVars.ShadowElementPressed]: `1px 1px 2px var(${ThemeVars.ShadowColorLight}), inset 1px 1px 2px var(${ThemeVars.ShadowColorDark})`,
  [ThemeVars.ShadowSurface]: `0px 1px 4px rgba(13, 2, 72, 0.35)`,
  [ThemeVars.ShadowTooltip]: `0px 1px 4px rgba(13, 2, 72, 0.35)`,
  [ThemeVars.ShadowTab]: `0px 1px 1px rgba(0, 0, 0, 0.1)`,
  [ThemeVars.ShadowDropdown]: `0px 4px 8px rgba(19, 19, 19, 0.15)`,
  [ThemeVars.ShadowMobileTapBar]: `0px -4px 8px rgba(19, 19, 19, 0.15)`,
  [ThemeVars.ShadowMobileSideMenu]: `-4px 4px 8px rgba(19, 19, 19, 0.15)`,
})

export function overrideDefaultPreset(overrides: Partial<ThemePreset>): ThemePreset {
  return { ...THEME_DEFAULT, ...overrides }
}
