import { defineThemePreset, ThemeVars } from './core'

/**
 * TODO fix scss var references
 */
export default defineThemePreset({
  [ThemeVars.BrandSoramitsuRed]: '',
  [ThemeVars.BrandPMSBlack]: '',
  [ThemeVars.BrandUltraBlack]: '',
  [ThemeVars.BrandWhite]: '',
  [ThemeVars.BrandPolkaswapPink]: '',
  [ThemeVars.ColorThemeAccent]: `#D0021B`,
  [ThemeVars.ColorThemeAccentHover]: `#C6021A`,
  [ThemeVars.ColorThemeAccentPressed]: `#BB0218`,
  [ThemeVars.ColorThemeAccentFocused]: `#B10217`,
  [ThemeVars.ColorThemeSecondary]: `#FAE6E8`,
  [ThemeVars.ColorThemeSecondaryHover]: `#F6CCD1`,
  [ThemeVars.ColorThemeSecondaryPressed]: `#F1B3BB`,
  [ThemeVars.ColorThemeSecondaryFocused]: `#EC9AA4`,
  [ThemeVars.ColorBaseContentPrimary]: `#2D2926`,
  [ThemeVars.ColorBaseContentSecondary]: `#53565A`,
  [ThemeVars.ColorBaseContentTertiary]: `#75787B`,
  [ThemeVars.ColorBaseContentQuaternary]: `#A3A4A8`,
  [ThemeVars.ColorBaseBackground]: `#F5F7F8`,
  [ThemeVars.ColorBaseDarkBackground]: `#4E4E4E`,
  [ThemeVars.ColorBaseBorderPrimary]: `#DDE0E1`,
  [ThemeVars.ColorBaseBorderSecondary]: `#ECEFF0`,
  [ThemeVars.ColorBaseBackgroundHover]: `#ECEFF0`,
  [ThemeVars.ColorBaseDisabled]: `#F5F7F8`,
  [ThemeVars.ColorBaseOnDisabled]: `#75787B`,
  [ThemeVars.ColorBaseOnAccent]: `#FFFFFF`,
  [ThemeVars.ColorUtilityBody]: `#FFFFFF`,
  [ThemeVars.ColorUtilitySurface]: `#FFFFFF`,
  [ThemeVars.ColorUtilityOverlay]: `rgba(0, 0, 0, 0.45)`,
  [ThemeVars.ColorStatusSuccess]: `#009900`,
  [ThemeVars.ColorStatusWarning]: `#FF9900`,
  [ThemeVars.ColorStatusError]: `#FF0000`,
  [ThemeVars.ColorStatusSuccessBackground]: `#CCEDCC`,
  [ThemeVars.ColorStatusWarningBackground]: `#FFE3B8`,
  [ThemeVars.ColorStatusErrorBackground]: `#FFF9FA`,

  // font size

  [ThemeVars.FontSizeD1]: '40px',
  [ThemeVars.FontSizeD2]: '30px',

  [ThemeVars.FontSizeH1]: '36px',
  [ThemeVars.FontSizeH2]: '30px',
  [ThemeVars.FontSizeH3]: '24px',
  [ThemeVars.FontSizeH4]: '18px',
  [ThemeVars.FontSizeH5]: '16px',
  [ThemeVars.FontSizeH6]: '14px',
  [ThemeVars.FontSizeH7]: '12px',

  [ThemeVars.FontSizeCH1]: '14px',
  [ThemeVars.FontSizeCH2]: '12px',
  [ThemeVars.FontSizeCH3]: '10px',

  [ThemeVars.FontSizeP1]: '16px',
  [ThemeVars.FontSizeP2]: '14px',
  [ThemeVars.FontSizeP3]: '14px',
  [ThemeVars.FontSizeP4]: '12px',

  [ThemeVars.FontSizeSingleline]: '15px',

  // end font size

  [ThemeVars.LineHeightReset]: `1`,
  [ThemeVars.LineHeightMini]: `1.2`,
  [ThemeVars.LineHeightExtraSmall]: `1.25`,
  [ThemeVars.LineHeightSmall]: `1.3`,
  [ThemeVars.LineHeightBase]: `1.4`,
  [ThemeVars.LineHeightMedium]: `1.5`,
  [ThemeVars.LineHeightBig]: `1.8`,
  [ThemeVars.LetterSpacingMini]: `-0.04em`,
  [ThemeVars.LetterSpacingSmall]: `-0.02em`,
  [ThemeVars.LetterSpacingMedium]: `-0.01em`,
  [ThemeVars.LetterSpacingBig]: `0.01em`,
  [ThemeVars.LetterSpacingLarge]: `0.03em`,
  [ThemeVars.LetterSpacingExtraLarge]: `0.06em`,
  [ThemeVars.FontFeatureSettingsCommon]: `"tnum" on, "lnum" on, "case" on, "salt" on, "ss01" on`,
  [ThemeVars.FontFeatureSettingsHeading]: `"tnum" on, "lnum" on, "salt" on, "case" on`,
  [ThemeVars.FontFeatureSettingsCapsHeading]: `"tnum" on, "lnum" on, "case" on`,
  [ThemeVars.FontFeatureSettingsCaps]: `"case" on`,
  [ThemeVars.FontFeatureSettingsSingleline]: `"salt" on, "case" on`,
  [ThemeVars.FontFeatureSettingsCardTitle]: `"tnum" on, "lnum" on, "ss01" on`,
  [ThemeVars.FontFeatureSettingsInput]: `"tnum" on, "lnum" on`,
  [ThemeVars.FontFeatureSettingsButton]: `"tnum" on, "lnum" on, "salt" on`,
  [ThemeVars.SizeMini]: `24px`,
  [ThemeVars.SizeSmall]: `32px`,
  [ThemeVars.SizeMedium]: `40px`,
  [ThemeVars.SizeBig]: `56px`,
  [ThemeVars.BasicSpacing]: `8px`,
  [ThemeVars.BorderRadiusMini]: `$s-border-radius-base`,
  [ThemeVars.BorderRadiusSmall]: `$s-border-radius-base * 2`,
  [ThemeVars.BorderRadiusMedium]: `$s-border-radius-base * 3`,
  [ThemeVars.BorderRadiusBig]: `$s-border-radius-base * 4`,
  [ThemeVars.ShadowColorDark]: `rgba(0, 0, 0, 0.1)`,
  [ThemeVars.ShadowTokenIcon]: '?',
  [ThemeVars.ShadowColorDarkLight]: `rgba(0, 0, 0, 0.02)`,
  [ThemeVars.ShadowColorLight]: `rgba(255, 255, 255, 1)`,
  [ThemeVars.ShadowColorLightDark]: `rgba(255, 255, 255, 0.8)`,
  [ThemeVars.ShadowElement]: `-1px -1px 1px $s-shadow-color-dark-light, 1px 1px 3px $s-shadow-color-dark, inset 1px 1px 2px $s-shadow-color-light-dark`,
  [ThemeVars.ShadowElementPressed]: `1px 1px 2px $s-shadow-color-light, inset 1px 1px 2px $s-shadow-color-dark`,
  [ThemeVars.ShadowSurface]: `0px 1px 4px rgba(13, 2, 72, 0.35)`,
  [ThemeVars.ShadowTooltip]: `0px 1px 4px rgba(13, 2, 72, 0.35)`,
  [ThemeVars.ShadowTab]: `0px 1px 1px rgba(0, 0, 0, 0.1)`,
  [ThemeVars.ShadowDropdown]: `0px 4px 8px rgba(19, 19, 19, 0.15)`,
  [ThemeVars.ShadowMobileTapBar]: `0px -4px 8px rgba(19, 19, 19, 0.15)`,
  [ThemeVars.ShadowMobileSideMenu]: `-4px 4px 8px rgba(19, 19, 19, 0.15)`,
})
