export enum Components {
  SApp = 'SApp',
  SAside = 'SAside',
  SButton = 'SButton',
  SButtonGroup = 'SButtonGroup',
  SCard = 'SCard',
  SCol= 'SCol',
  SContainer = 'SContainer',
  SFooter = 'SFooter',
  SForm = 'SForm',
  SFormItem = 'SFormItem',
  SHeader = 'SHeader',
  SInput = 'SInput',
  SJsonInput = 'SJsonInput',
  SMain = 'SMain',
  SMenu = 'SMenu',
  SMenuItem = 'SMenuItem',
  SMenuItemGroup = 'SMenuItemGroup',
  SRow = 'SRow',
  SScrollSectionItem = 'SScrollSectionItem',
  SScrollSections = 'SScrollSections',
  SSubmenu = 'SSubmenu',
  STooltip = 'STooltip'
}
