import Vue from 'vue'

export type SFCWithInstall<T> = T & { install(vue: typeof Vue): void }

export enum Components {
  SApp = 'SApp',
  SAside = 'SAside',
  SBreadcrumb = 'SBreadcrumb',
  SBreadcrumbItem = 'SBreadcrumbItem',
  SButton = 'SButton',
  SButtonGroup = 'SButtonGroup',
  SCard = 'SCard',
  SCheckbox = 'SCheckbox',
  SCol= 'SCol',
  SCollapse = 'SCollapse',
  SCollapseItem = 'SCollapseItem',
  SContainer = 'SContainer',
  SDatePicker = 'SDatePicker',
  SDesignSystemProvider = 'SDesignSystemProvider',
  SDialog = 'SDialog',
  SDivider = 'SDivider',
  SDropdown = 'SDropdown',
  SDropdownItem = 'SDropdownItem',
  SFooter = 'SFooter',
  SForm = 'SForm',
  SFormItem = 'SFormItem',
  SHeader = 'SHeader',
  SIcon = 'SIcon',
  SInput = 'SInput',
  SFloatInput = 'SFloatInput',
  SJsonInput = 'SJsonInput',
  SMain = 'SMain',
  SMenu = 'SMenu',
  SMenuItem = 'SMenuItem',
  SMenuItemGroup = 'SMenuItemGroup',
  SOption = 'SOption',
  SOptionGroup = 'SOptionGroup',
  SPagination = 'SPagination',
  SRadio = 'SRadio',
  SRadioGroup = 'SRadioGroup',
  SRow = 'SRow',
  SScrollSectionItem = 'SScrollSectionItem',
  SScrollSections = 'SScrollSections',
  SSelect = 'SSelect',
  SSlider = 'SSlider',
  SSubmenu = 'SSubmenu',
  SSwitch = 'SSwitch',
  STab = 'STab',
  STabs = 'STabs',
  STable = 'STable',
  SHierarchicalTable = 'SHierarchicalTable',
  STableColumn = 'STableColumn',
  STooltip = 'STooltip'
}
